version: "3"
volumes:
  mysql_data:
  wordpress_data:

services:
  db:
    image: mysql:5.7
	  volumes:
	    - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
	    MYSQL_DATABASE: wordpress
	    MYSQL_USER: wordpressuser
      MYSQL_DATABASE: wordpress
   
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
	  volumes:
	   - wordpress_data:/var/www/html
	  ports:
      - 8085:80
	  restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: wordpress
